[workspace]
members = [".", "alarm-server"]
[workspace.package]
version = "0.8.4"
edition = "2024"
description = "a simple tool to compute time: easy to config, and easy to use."
license-file = "LICENSE"
readme = "README.md"
keywords = ["timer"]
repository = "https://github.com/jm-observer/timer-util"
documentation = "https://docs.rs/timer-util/latest/timer-util/"
homepage = "https://docs.rs/timer-util/latest/timer-util/"


[package]
name = "timer-util"
version.workspace = true
edition.workspace = true
license-file.workspace = true

include = [
    "LICENSE", "Cargo.toml", "README.md", "src/*.rs", "examples/*.rs"
]

[features]
default = []
serde = ["dep:serde"]

[dependencies]
log = { version = "0.4" }
chrono = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
tokio = {version ="1.18", features = ["rt-multi-thread", "macros", "time"]}
serde_json = "1"
